project:
  name: quickstart-boomi-eks-molecule
  owner: quickstart-eng@amazon.com
  regions:
  - eu-north-1
  - me-south-1
  - us-east-1
  - us-east-2
  - us-west-2
  template: templates/boomi-eks-master.template.yaml
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  existing-vpc:
    regions:
      - us-east-2
    parameters:
      VPCID: $[taskcat_ssm_/taskcat/params/vpc/id]
      PrivateSubnet1ID: $[taskcat_ssm_/taskcat/params/vpc/private_subnet/1a/id]
      PrivateSubnet2ID: $[taskcat_ssm_/taskcat/params/vpc/private_subnet/2a/id]
      PrivateSubnet3ID: $[taskcat_ssm_/taskcat/params/vpc/private_subnet/3a/id]
      PublicSubnet1ID: $[taskcat_ssm_/taskcat/params/vpc/public_subnet/1/id]
      PublicSubnet2ID: $[taskcat_ssm_/taskcat/params/vpc/public_subnet/2/id]
      PublicSubnet3ID: $[taskcat_ssm_/taskcat/params/vpc/public_subnet/3/id]
      BoomiAccountID: override
      BoomiPassword: override
      BoomiUsername: override
      MoleculeFQDN: override
      HostedZoneID: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    template: templates/existing.template.yaml
  # helm-charts:
  #   regions:
  #     - us-east-2
  #   parameters:
  #     BoomiAccountID: override
  #     BoomiPassword: override
  #     BoomiUsername: override
  #     QSS3BucketName: $[taskcat_autobucket]
  #     QSS3BucketRegion: $[taskcat_current_region]
  #     ClusterName: $[taskcat_ssm_/taskcat/params/eks/cluster_name]
  #     LoadBalancerType: $[taskcat_ssm_/taskcat/params/boomi-eks-molecule/lb-type]
  #   template: templates/boomi-eks-molecule.template.yaml
