project:
  name: quickstart-boomi-eks-molecule
  owner: quickstart-eng@amazon.com
  regions:
  - eu-north-1
  - me-south-1
  - us-east-1
  - us-east-2
  - us-west-2
  template: templates/boomi-eks-master.template.yaml
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  new-vpc:
    regions:
      - us-east-2
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      KeyPairName: cikey
      BoomiAccountID: $[taskcat_ssm_/qs/eks-boomi-molecule/params/boomi_account_id]
      BoomiPassword: $[taskcat_ssm_/qs/eks-boomi-molecule/params/boomi_pass]
      BoomiUsername: $[taskcat_ssm_/qs/eks-boomi-molecule/params/boomi_user]
      MoleculeFQDN: $[taskcat_ssm_/qs/eks-boomi-molecule/params/fqdn]
      HostedZoneID: $[taskcat_ssm_/qs/eks-boomi-molecule/params/hosted_zone]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 127.0.0.1/32
    template: templates/new-main.template.yaml
